# Generated by Django 4.0.1 on 2022-01-17 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=115, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True)),
                ('protection', models.CharField(choices=[('NO', 'None'), ('LO', 'Locked'), ('NC', "Locked and doesn't allow children")], default='NO', help_text="Setting the protection to 'locked' will not allow others to edit this page in the future.", max_length=2)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='wiki.page')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=115, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('edit_number', models.PositiveSmallIntegerField(default=0, unique=True)),
                ('edit_summary', models.CharField(blank=True, max_length=255, null=True)),
                ('latest', models.BooleanField(default=False)),
                ('patch', models.TextField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision', to='wiki.page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='wiki.revision')),
            ],
            options={
                'ordering': ['-latest', 'created_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('parent', 'title'), name='unique_page_title'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('parent', 'slug'), name='unique_page_slug'),
        ),
    ]
