# Generated by Django 4.0.1 on 2022-01-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
    ]
