# Generated by Django 4.0.1 on 2022-05-26 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_alter_revision_edit_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revision',
            options={'ordering': ['-latest', '-created_date']},
        ),
        migrations.AlterField(
            model_name='revision',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions_parent', to='wiki.page'),
        ),
    ]
