# Generated by Django 4.0.1 on 2022-05-26 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='users',
            field=models.ManyToManyField(related_name='neighborhoods', to=settings.AUTH_USER_MODEL),
        ),
    ]
