# Generated by Django 4.0.1 on 2022-05-27 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_alter_neighborhood_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='distribution.neighborhood'),
        ),
    ]
