# Generated by Django 4.0.1 on 2022-08-09 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distribution', '0004_alter_neighborhood_slug_area_location_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterField(
            model_name='location',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='distribution.area'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='neighborhoods', to=settings.AUTH_USER_MODEL),
        ),
    ]
