# Generated by Django 4.0.1 on 2022-08-09 17:07

from django.db import migrations, models
import django.utils.timezone
import poster_calendar.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('put_up_date', models.DateField(default=django.utils.timezone.now)),
                ('take_down_date', models.DateField(blank=True, default=poster_calendar.models.get_take_down_date, null=True)),
            ],
            options={
                'ordering': ['take_down_date'],
            },
        ),
    ]
