# Generated by Django 4.0.1 on 2022-08-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0005_alter_location_options_alter_location_area_and_more'),
        ('poster_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='neighborhoods',
            field=models.ManyToManyField(related_name='posters', to='distribution.Neighborhood'),
        ),
    ]
