# Generated by Django 4.0.1 on 2022-08-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster_calendar', '0002_poster_neighborhoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='poster_type',
            field=models.BooleanField(choices=[(True, 'Poster'), (False, 'Handbill')], default=True, verbose_name='type'),
        ),
    ]
