# Generated by Django 4.0.1 on 2022-05-26 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockOutResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField(default=0, verbose_name='Week Number')),
                ('completed_route', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Completed route?')),
                ('need_someone', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Do you need someone to complete this route for you?')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes about route/this week')),
                ('submited', models.DateTimeField(default=django.utils.timezone.now)),
                ('neighborhoods', models.ManyToManyField(to='distribution.Neighborhood', verbose_name='Neighborhoods on route')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Name')),
            ],
        ),
    ]
