# Generated by Django 4.0.1 on 2022-05-27 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clockoutresponse',
            options={'ordering': ['-week_number', '-submitted']},
        ),
        migrations.RenameField(
            model_name='clockoutresponse',
            old_name='submited',
            new_name='submitted',
        ),
        migrations.AlterField(
            model_name='clockoutresponse',
            name='week_number',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)], verbose_name='Week Number'),
        ),
    ]
